//
// Created by sjh on 2024/12/8.
//

/**
#ifndef APIDEMO_COM_pkgname_JAVA2CJNI_H
#define APIDEMO_COM_pkgname_JAVA2CJNI_H

#endif //APIDEMO_COM_pkgname_JAVA2CJNI_H
*/



/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_pkgname_Java2CJNI */

#ifndef _Included_com_pkgname_Java2CJNI     // 目的是 头文件只被include一次
#define _Included_com_pkgname_Java2CJNI

    #ifdef __cplusplus
    extern "C" {
    #endif
    /*
     * Class:     com_pkgname_Java2CJNI
     * Method:    javaMethod
     * Signature: ()Ljava/lang/String;
     *
     *     c方法名 = Java_包名_类名_方法名
     *     JNIEnv是jni环境，
           jobject指的是调用native方法的对象
        第一个参数JNIEnv是   指向可用JNI函数表的接口指针，
        第二个参数jobject是  Java函数所在类的实例的Java对象引用。
     */
    JNIEXPORT jstring JNICALL Java_com_pkgname_Java2CJNI_javaMethod
      (JNIEnv *, jobject);

    JNIEXPORT jint JNICALL Java_com_pkgname_Java2CJNI_javaIncrease
      (JNIEnv *, jclass, jint);


    #ifdef __cplusplus
    }
    #endif

#endif
